from app import db, app
from app.models import IncomeExpenses
from dotenv import load_dotenv
from datetime import datetime, timedelta

# Load environment variables from .env file
load_dotenv()

with app.app_context():
    db.create_all()
    print("Database initialized")
    print("\n--------------------")
    print("Add Entries")
    print("\n--------------------")

    entry1 = IncomeExpenses(amount=1000, category="salary", description="Salary", date=datetime.now() - timedelta(days=19))
    entry2 = IncomeExpenses(amount=500, category="rent", type="expense", description="Rent", date=datetime.now() - timedelta(days=18))
    entry3 = IncomeExpenses(amount=100, category="transport", type="expense", description="Transport", date=datetime.now() - timedelta(days=17))
    entry4 = IncomeExpenses(amount=20, category="food", type="expense", description="Groceries", date=datetime.now() - timedelta(days=16))
    entry5 = IncomeExpenses(amount=50, category="utilities", type="expense", description="Electricity bill", date=datetime.now() - timedelta(days=15))
    entry6 = IncomeExpenses(amount=1500, category="salary", description="Monthly salary", date=datetime.now() - timedelta(days=14))
    entry7 = IncomeExpenses(amount=30, category="transport", type="expense", description="Gasoline", date=datetime.now() - timedelta(days=13))
    entry8 = IncomeExpenses(amount=100, category="freelance", description="Freelance project", date=datetime.now() - timedelta(days=12))
    entry9 = IncomeExpenses(amount=40, category="entertainment", type="expense", description="Movie tickets", date=datetime.now() - timedelta(days=11))
    entry10 = IncomeExpenses(amount=60, category="food", type="expense", description="Restaurant", date=datetime.now() - timedelta(days=10))
    entry11 = IncomeExpenses(amount=200, category="bonus", description="Work bonus", date=datetime.now() - timedelta(days=9))
    entry12 = IncomeExpenses(amount=70, category="utilities", type="expense", description="Internet bill", date=datetime.now() - timedelta(days=8))
    entry13 = IncomeExpenses(amount=25, category="transport", type="expense", description="Public transport", date=datetime.now() - timedelta(days=7))
    entry14 = IncomeExpenses(amount=50, category="gifts", type="expense", description="Birthday gift", date=datetime.now() - timedelta(days=6))
    entry15 = IncomeExpenses(amount=300, category="investment", description="Stock investment", date=datetime.now() - timedelta(days=5))
    entry16 = IncomeExpenses(amount=80, category="health", type="expense", description="Pharmacy", date=datetime.now() - timedelta(days=4))
    entry17 = IncomeExpenses(amount=120, category="shopping", type="expense", description="New clothes", date=datetime.now() - timedelta(days=3))
    entry18 = IncomeExpenses(amount=10, category="food", type="expense", description="Coffee", date=datetime.now() - timedelta(days=2))
    entry19 = IncomeExpenses(amount=90, category="utilities", type="expense", description="Water bill", date=datetime.now() - timedelta(days=1))
    entry20 = IncomeExpenses(amount=1800, category="salary", description="Monthly salary", date=datetime.now())
    entry21 = IncomeExpenses(amount=45, category="transport", type="expense", description="Taxi", date=datetime.now() - timedelta(days=1))
    entry22 = IncomeExpenses(amount=150, category="freelance", description="Freelance writing", date=datetime.now() - timedelta(days=2))
    entry23 = IncomeExpenses(amount=35, category="entertainment", type="expense", description="Concert", date=datetime.now() - timedelta(days=3))
    entry24 = IncomeExpenses(amount=55, category="food", type="expense", description="Lunch", date=datetime.now() - timedelta(days=4))
    entry25 = IncomeExpenses(amount=250, category="bonus", description="Performance bonus", date=datetime.now() - timedelta(days=5))
    entry26 = IncomeExpenses(amount=75, category="utilities", type="expense", description="Gas bill", date=datetime.now() - timedelta(days=6))
    entry27 = IncomeExpenses(amount=20, category="transport", type="expense", description="Bus fare", date=datetime.now() - timedelta(days=7))
    entry28 = IncomeExpenses(amount=60, category="gifts", type="expense", description="Wedding gift", date=datetime.now() - timedelta(days=8))

    print("\nEntries:")
    print(entry1)
    print(entry2)
    print(entry3)
    print(entry4)
    print(entry5)
    print(entry6)
    print(entry7)
    print(entry8)
    print(entry9)
    print(entry10)
    print(entry11)
    print(entry12)
    print(entry13)
    print(entry14)
    print(entry15)
    print(entry16)
    print(entry17)
    print(entry18)
    print(entry19)
    print(entry20)
    print(entry21)
    print(entry22)
    print(entry23)
    print(entry24)
    print(entry25)
    print(entry26)
    print(entry27)
    print(entry28)

    db.session.add(entry1)
    db.session.add(entry2)
    db.session.add(entry3)
    db.session.add(entry4)
    db.session.add(entry5)
    db.session.add(entry6)
    db.session.add(entry7)
    db.session.add(entry8)
    db.session.add(entry9)
    db.session.add(entry10)
    db.session.add(entry11)
    db.session.add(entry12)
    db.session.add(entry13)
    db.session.add(entry14)
    db.session.add(entry15)
    db.session.add(entry16)
    db.session.add(entry17)
    db.session.add(entry18)
    db.session.add(entry19)
    db.session.add(entry20)
    db.session.add(entry21)
    db.session.add(entry22)
    db.session.add(entry23)
    db.session.add(entry24)
    db.session.add(entry25)
    db.session.add(entry26)
    db.session.add(entry27)
    db.session.add(entry28)

    print("\n--------------------")
    print("\nEntries added")
    db.session.commit()

    print("\n--------------------")
    print("\nDatabase initialized")
    print("\n--------------------")
    print("\nAccess all entries")
    print("\n--------------------")
    print("\n")

    all_entries = IncomeExpenses.query.all()
    for entry in all_entries:
        print(entry)

    print("\n--------------------")
