[phases.setup]
nixPkgs = ["curl", "wget", "gcc", "gnumake"]

[phases.install]
commands = [
    "curl -LsSf https://astral.sh/uv/install.sh | sh",
    "export PATH=\"/root/.local/bin:${PATH}\"",
    "uv sync --group prod"
]

[start]
cmd = "uv run gunicorn --bind 0.0.0.0:3000 --workers 3 --access-logfile - --error-logfile - --log-level info config.wsgi:application"

[build.args]
SECRET_KEY = ""
DATABASE_URI = ""

[build.environment]
PATH = "/root/.local/bin:${PATH}"