# nixpacks.toml
providers = ["python"]

[phases.setup]
cmds = [
    "apt-get update && apt-get install -y python3-venv",
    "python3 -m venv /app/.venv"
]

[phases.install]
cmds = [
    ". /app/.venv/bin/activate && pip install --upgrade pip",
    ". /app/.venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = ". /app/.venv/bin/activate && gunicorn --bind 0.0.0.0:$PORT main:app"

[build.args]
NIXPACKS_PYTHON_VERSION = "3.12"
