[phases.setup]
cmds = [
    "apt-get update && apt-get install -y python3 python3-pip python3-venv"
]

[phases.install]
cmds = [
    "pip3 install -r requirements.txt",
    "npm install",
    "npm install -g @tailwindcss/cli"
]

[phases.build]
cmds = [
    "tailwindcss -i app/static/src/input.css -o app/static/dist/style.css --minify"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT main:app --workers 4 --threads 2"

[env]
PYTHONUNBUFFERED = "1"
FLASK_APP = "main:app"
FLASK_ENV = "production"

[build.args]
NIXPACKS_PYTHON_VERSION = "3.12"